# _config.post.yml 中的配對所有“文章”生效
sidebar:
  left:
    sticky: true
  right:
    sticky: false
widgets:
  #- position: left
  #  type: profile
  #- position: left
  #  type: links
  - position: right
    type: toc
  - position: right
    type: recent_posts
  #  - position: left
  #    type: archives
  - position: right
    type: tags
  - position: right
    type: categories
