# _config.post.yml中的配對所有“文章”生效
sidebar:
  left:
    sticky: false
  right:
    sticky: true
widgets:
  #- position: left
  #  type: profile
  #- position: left
  #  type: links
  - position: right
    type: toc
 # - position: left
 #   type: categories
  - position: right
    type: recent_posts
#  - position: left
#    type: archives
  - position: right
    type: tags
